### ISSUE TITLE
Feature request, multiple camel command at once and set carry all by default

### ISSUE THREAD

**Issue by meepeek** [the3dfxdude/7kaa#184] opened 2020-02-05 09:08 UTC
1. Currently, we need to set route to each individual camel to pick up goods at way points, select multiple camel and set routes applies only on the active one. It would be nice if we could select multiple camel and once we give them the routes, it relays to every selected camel.
2. Also pick up everything should be default. Currently, if there were no goods there's no option for pickup and pickup none is by default.

**Comment by the3dfxdude** [comment] 2020-03-19 01:07
1. I think the issue is more to do with to point and clicks, which usually means you have to hunt for the right market using the map or arrow keys, which you have to do first before you click set stop, then hunt back to each camel and do the set stop, and then clicking back and forth.

A multiple selection and set stop interface just isn't going to work well. It would have to require a major redesign of UI, and not really gain much, because that isn't what people ought to be doing. They should be thinking more on how to make money at trade.

So I had alerady been thinking another way that works in the existing design. I was considering reworking the Trade report, and possibly making a way to list the markets open to trade, their goods, and most of the Camel option all available all the same screen. I mean, there was something very similar in Capitalism, that there was a way to select suppliers through the report interface. We got the report interface in 7K, but none of the management interface integration.

Also, either add a copy and paste, or a click and drag selection for quick duplication on stops and product choices.

2. The 'A' button is not a pick up everything button. It's an "Auto" setting. It is only really something you use to spread out your commodities, or how the AI does trade. Defaulting to 'A' doesn't work either. Try setting all your camels to 'A' and set up a bunch of different links. It's going to neuter much of your ability to do anything meaningful with trade.

**Comment by J-Moravec** [comment] 2020-03-19 01:24
I was thinking about it and looking at the code what would be possible.

The simplest solution I have found, one that would require the least change in UI, but provide the biggest increase in making trade more possible, would be:

a) Make "Auto" always the default setting, always available and make more sensible rules:

- for other kingdom's markets (take everything)
- for kingdom's own markets (take stuff depending on demand and availability)
- possibly some new rule for raw resources, but it hard to judge for game where is raw resource demand and where is raw resource production.

This way the "Auto" would be a good choice for almost all situations, even when market gets more products than when the trade route was setup, so no need to reset it. Still, player will have a choice to fine-tune their trade rules.

b) Clone caravan button

While a more involved caravan trade-route setup where all caravans would be grouped into a route and it could be controlled from the trade screen would be very nice, making just clone caravan button bundled with a sensible "Auto" option would be sufficient in most situations. Deleting and recloning bad trade caravans is a sensible solution.

Thats 2 function that need to be changed + UI changes. Its on my TODO list, so maybe once the emergency shutdown is declared here I will have enough time ^_^

**Comment by the3dfxdude** [comment] 2020-03-19 03:18
* for other kingdom's markets (take everything)
That isn't a good idea. Take the usual game scenario where each player has one type of resource. Player A has copper products, and Player B has iron products. Player A imports the iron products, and Player B imports the copper products. As soon as Player A brings back the iron product to his market, Player B can now be picking up iron products he is already producing locally, and not pickup copper products anymore. Which brings to the point why the original UI does it this way. If you set up the trade routes as soon as you open your market or other firms, and you usually are intending to move product one way, and the firm UI as it is will make you pick where to pull product and automatically set to that, and not change that from out from under you. And the new firm you are bringing product to will have nothing selected since usually it isn't going to be two way.

* for kingdom's own markets (take stuff depending on demand and availability)
Which you can do anytime with the 'A' setting. But generally speaking, that is not what I do. The reason is simple. There are only so many places that have factories and they won't be next to towns. You need to make sure that product moves from the factories to all of the towns. That can be made easier simply if you can have a global overview where you can see everything. The initial set up works fine, but you don't have an easy way to keep the routes going for too long into the game.

I think 7K2 generally defaulted to 'A' with no other changes. But I don't want to start doing this like 7K2.

* possibly some new rule for raw resources, but it hard to judge for game where is raw resource demand and where is raw resource production.

Exactly. But this is the same issue when dealing with products too, which I just mentioned above. If the report did a better job of explaining what is happening, and if you can just select and change it all at once, then managing will go so much better.

My ask is that we address the report screen and give detailed enough info with buttons to control things, and not change how pickup works.

**Comment by J-Moravec** [comment] 2020-03-19 03:48
> That isn't a good idea.

Thats what I do and I would argue that it is a correct medium to long-term strategy unless you are actively hurting for money. It's much easier to expand your own product demand (selling to neutral villages or try to increase your population, which you want to do anyway) and thus getting twice the amount of money in return, than letting AI get your goods.

Maybe with a better trade routes it might be different (given the huge running cost of mine alone): getting as much money ASAP and using that to aggressively expand and claim new goods when they appear, but in my experience, this require a bit too much micro at the moment, so monopolizing my own source of goods seems like a better strategy.

Funny thing, when playing my way, it is very easy to generate huge trade exchange by constantly buying and selling the same bag of goods.:)

> Which you can do anytime with the 'A' setting. But generally speaking, that is not what I do. 

Me neither, because "Auto" is generally quite stupid and doesn't do what I want to do that well. By making the "Auto" option smarter, we could manage that. Notably because it doesn't matter much in the long-term where you sell your goods, if you sell your goods enough. Currently, the "Auto" option doesn't do good-enough job and is not activated by default, only when you have two or more products. So it can't autobalance single resource for example.

> Exactly on the judging part being hard.

But there are some good rules one can design around a required behaviour. And if they are in "Auto", they are also resistant against future market changes. Which would significantly improve AI.


Game is already checking demand. It would be easy to add a counter for production and consumption and include caravans in this. And add counter for production and consumption of raw resources as well. These way you can create some kind of flow mechanics, where caravans work as edges in your graph and the network will try to balance itself to spread the resources in a most efficient way. This would even solve the problem with a transit stations.

Never mind, I think I am sitting next to mathematicians/CS people for too long.

**Comment by the3dfxdude** [comment] 2020-04-18 23:23
Well, if you have a specific example, we can study how to incorporate it. We should study the AI, and how it works, and find if they do more than use the auto-pick up product balancing. If the AI is missing something obvious, then probably there is something here in what you are saying. But I think you are speaking of a different issue. The requester is asking for a UI change.

I don't agree about just changing the default mode to auto pick up, because auto-balancing doesn't make sense. The UI works fine in the early game for how people are supposed to play. It's the late game that it basically falls apart. That is why I want to move the trade configuration into the trade report, and also give a good listing of available markets without needing to jump to the map. Capitalism does this, I don't know why it didn't make it into this game. Sorry I don't think issuing multiple orders is really going to work in the game design or help either.

**Comment by the3dfxdude** [comment] 2020-06-22 02:28
The UI of the Trade Report has been improved. This doesn't improve the intelligence of the caravans, but it helps you make trade routes alot faster than the original interface.

**Comment by the3dfxdude** [comment] 2020-06-24 04:04
I've been reviewing the request. I'll answer again based on my current thoughts.

1. Issue multiple orders or cloning the pick up routes. I don't see this as a practical thing to do. Having multiple caravans sent on the same route might be a thing for a long distance haul, but the market you are pulling from will have a max product store and a rate of replenishing, and the destination also has a max store. Whenever I doubled up on my routes, I generally spaced it out anyway, and I don't create all the caravans and the routes simultaneously. So adding this functionality makes little to gain.

2. The default should be auto when setting a stop. I think we need to define what should happen when you create a caravan. Usually it is for moving a product from the origin or picking up somewhere remote. The first stop is automatically created for the origin, and the products available selected. The second stop you pick, and the products available selected. Usually you are moving one type of product one way, so you disable that product at the other location. The default if the market has more than 1 product is auto already. The only time it isn't if it only has 1 production (defaults to the product), or it has no product, then defaults to none. If you are setting a stop at a market that has no product, then realistically, do you expect to pick up there? Again setting everything auto pretty much means you don't care, and anything could happen.

I guess the issue isn't so much that auto isn't a default (it sort of is if you really are trying to shop around at markets that have products as you expect). It's that the early markets have nothing much to buy from, and do not default to auto. If you have a specific nuance of why auto is not easy enough to get there, please explain. I guess it doesn't always show the button, when the market is limited.

**Comment by J-Moravec** [comment] 2020-06-24 04:21
I have to strongly disagree with you. To create a new caravan from scratch, you need to click on market, click on create caravan, click on new caravan, click on setup new route, click on target market, and often you need to click on various goods depending on what your guy is doing. Thats at minimum 5 clicks for every new caravan you will make. Compared to clone caravan, thats one click. Whenever you are trying to saturate a new trade route, this would save huge amount of hassle.

Regarding mass command, I can imagine situation where a new goods is available in some market, so you need to reasign all your caravans. This would be much easier if you could select all those caravans and assign the pick up of new goods, rather than selecting all of them individually. With box selection, you can do as little as two click, compared to 2n.

Regarding auto, I think that the auto option should be future proof and thus a reasonable option should be designed with a reasonable expectation. This is less hassle if quality of life options that safe clicks (as those mentioned above) are implemented, but more hassle if any reassignment takes a lot of clicks. One could even put a different default behaviour in option menu, so a player could choose their preferred option (e.g., I think that all finished goods should be always picked up from enemy market, because I am hoarder and any goods sold by me to a my village is the best case and everything else is less desirable, but you do not think so).

**Comment by the3dfxdude** [comment] 2020-06-24 23:47
I think you missed what I said. Basically, I am saying there is no apparent need to mass command a bunch of caravans. If there was a need, that likely would have made it into the game per design and be part of the UI. Just looking at the constraints given when moving and storing products shows multiple caravans on a single route is questionable on the rate of return even if the UI was streamlined.

The other part you say on the hoarding strategy. I've done it myself and it's rather easy to accomplish without tons of caravans on the same route. Think about it.

So another words, the game designers didn't anticipate spamming markets to monopolize trade so it didn't make it as a UI. You could pull it on the AI sure, but if you tried to do it with me I'd end the treaty and be visiting you with my army. So this is really a thing because the AI doesn't care. In that sense, I think detecting this in the AI might be something to add so they can respond appropriately...

So I'm just going to say, look over the current UI, and let's talk about specifics if there UI quirks or obvious things that nag on the feel of doing trade. But right now, overhauling trade over something that wasn't really intended, is not something I want to affect the original design intent by. It's probably best to get people to spend more time with trade, with simple quality of life updates in the likeness the designers wanted.

**Closed by the3dfxdude** 2020-06-24 23:47 UTC

**Comment by J-Moravec** [comment] 2020-06-25 03:41
> I think you missed what I said.

No, I didn't miss what you have said. Regardless whether you think that having multiple caravans on the same route is a good idea or not, it is a pure fact that adding another caravan on the same route requires at least 5 clicks.

This annoyance significantly *limits* various strategies one can do. For example, setting a simple mining base (just mine, 8 villages, maybe fort) and transport mined minerals to your main base is quite annoying that it is often times more efficient just to build a local processing center there, with enough population that it also serves as a consumption centre.

Not even talking about the fact that if you have just a single caravan going left and right, you might not have
a) enough capacity to transport goods (especially in the late game, where the consumption can be quite large)
b) due to enemy caravans often picking goods, you might not even have any goods to pick up in the first place.

Having more caravans usually solve it. Even if you build your market next to their market and them pick everything (yes, I know these tricks).

> So another words, the game designers didn't anticipate spamming markets to monopolize trade so it didn't make it as a UI. 

Except the game designers essentially acknowledge how annoying this was by implementing the clone caravan into 7K2.

> but if you tried to do it with me I'd end the treaty and be visiting you with my army.

Except thats not how MP currently works, because interesting trade routes are often too annoying to set up.

> So this is really a thing because the AI doesn't care. In that sense, I think detecting this in the AI might be something to add so they can respond appropriately...

Except AI DOES care.
a) If you build market next to AI and buy all its goods (selling the finished goods to AI's own village), AI will declare war on you. This is one of the reason why I stopped doing that, because on the highest aggressivity level, I need to lay low as long as possible for my war machine production to kick in and slightly lower eco is not problem if I am able to trade small portion of war machines against enemy.

b) AI does the same to you. Not by building market next to you (although, sometimes...), but by taking away its own good, if you are able to hoard a sufficient supply.

>  It's probably best to get people to spend more time with trade, with simple quality of life updates in the likeness the designers wanted.

All I want is a clone caravan button. How is it not a simple quality of life feature that designers implemented in the sequel I have no idea.

**Comment by the3dfxdude** [comment] 2020-06-25 15:07
What transpired here:

1. The original request, to add multiple caravan commanding.
2. My response basically saying that's probably not going to help, there are other UI options that are easier.
3. You disagree strongly, saying it's important. But not really addressing multiple caravan commanding. There is discussion on other things.
4. My revisit with my late review saying that's probably not worth adding multiple caravan commanding.
5. You disagree strongly, and finally ending the last comment with "all I want is a clone caravan button".

This is why I said you are not listening. Come on, you are experienced in this game, and you do have good ideas. But I am trying to address the _requestor_, and make some progress here. Let's try not to derail it and let this be finished. This is why I'd rather have more open conversations using the forum than do it in a ticketing system.

I'll note the other things you are saying, and if you noticed my very first response to the requestor, "cloning" was always being considered as a possible UI change, but I still want to assess impact on the overall game play and game code. It's in my notes.

**Comment by the3dfxdude** [comment] 2020-06-25 15:25
BTW, columbo, based on your strategy if you want a UI change based on this specific thing you do, I want to spell out exactly what you are doing. Please bring it over the forum. I think I know basically what is happening there, but I want to see the details to be sure what to look for in testing. A video might help, but a replay file as well.
