### ISSUE TITLE
Killing general closes the game

### ISSUE THREAD

**Issue by astratow** [the3dfxdude/7kaa#231] opened 2022-03-06 05:06 UTC
As in the title: when general is killed by our spy, game closes. They kill our generals without any issues.

**Comment by the3dfxdude** [comment] 2022-03-07 00:03
Hello. I could not reproduce the issue here. I will need more information to work on this. Game version? Platform? Save file? Steps to make this happen?

**Comment by astratow** [comment] 2022-03-14 21:00
platform: Ubuntu 18.04.6 LTS
version 2.14.7
no save game
when playing against AI spy gets command kill and succesfully executes, game crashes. Will try to get report via application.

**Comment by the3dfxdude** [comment] 2022-03-15 00:00
That version is quite old. Please update.

**Comment by astratow** [comment] 2022-03-16 05:04
I tried, but compilation is failing. Do you know of any .deb binaries for newer version please? Many thanks in anticipation.

**Comment by the3dfxdude** [comment] 2022-03-16 23:17
I can't say which debs might be backwards compat, but there are several debs out there, like the 3 newest ubuntu releases: hirsute, impish, jammy

**Comment by robertpro** [comment] 2022-09-13 14:20
Try flatpak, I just tested it worked fine. https://flathub.org/apps/details/com.sevenkfans.sevenkaa

**Comment by the3dfxdude** [comment] 2023-09-14 22:26
No further update. Closing.

**Closed by the3dfxdude** 2023-09-14 22:26 UTC
