### ISSUE TITLE
Crash in multiplayer setup OSYS.cpp:1097

### ISSUE THREAD

**Issue by nathanielc** [the3dfxdude/7kaa#50] opened 2016-01-12 04:05 UTC
I compiled master 2ba326f21aeda50be798bca6734cbe02e60902f9 (./configure; make;) today and I am trying to play a multiplayer game. The multiplayer lobby works well the games connect but both clients crash when the game is started. I got out gdb and found the segfault to be on https://github.com/the3dfxdude/7kaa/blob/master/src/client/OSYS.cpp#L1097 for the machine hosting the game. The `this` pointer is null. The machine that is not hosting the game gets a similar segfault where the `this` pointer is null here https://github.com/the3dfxdude/7kaa/blob/master/src/client/OSYS.cpp#L1182 Looks like the Sys object is being freed too early or something. At that point I was at a loss as to how to fix it. Any direction would be nice. 

I compiled the game in debug mode and cannot reproduce the error. Makes sense because this is debug related code. For now I am just playing with debug mode and its working so far. 

Both hosts are Linux 64bit. Let me know if you need more info.

**Comment by the3dfxdude** [comment] 2016-01-12 18:34
Hi,

The Sys object does not deconstruct unless the game is exiting. This likely means you hit a prior error, and now the game is taking an abnormal exit path. But some of the cases simply leads to a hard crash, like what you report. Unfortunately this means that the real error is covered up.

Let me say this. 64-bit builds have not been tested in multiplayer. I do not expect them to work as the code has not been sanitized there. It likely will hit bugs even if all clients are 64-bit. There are likely bugs due to historic differences in compilers (MSVC6 vs modern GCC). I think the fastest way for you to prove this is to build 32-bit builds and test that.

Lastly, I do not recommend --enable-debug. This enables a DEBUG preprocessor flag enabling a bunch of legacy testing code, which includes stuff that may stress test the game. It was found that some of the code produces more problems than it was worth. I recommend not using --enable-debug unless you know what you are getting out of it. GCC is still passed -g without --enable-debug, so you can continue to use GDB there. That it is working in DEBUG mode, well, that should not happen...

**Comment by nathanielc** [comment] 2016-01-13 04:34
Great, I got a 32bit version compiled and running. I can play games with friends now! I did get two crashes after about 30min of play. If I can reproduce I'll add more details. Thanks

**Comment by the3dfxdude** [comment] 2016-01-13 19:33
I can reproduce the issue reported above. It appears to be a stack corruption occurring prior to the reported locations. I will fix this. Please open additional issues on new crashes.

**Comment by the3dfxdude** [comment] 2016-01-18 01:19
This is fixed in 7b8e0888d6583ace7887b9df27da1773a7ffac59. I can't guarantee bug free, but you should be able to start a match between 64-bit OS machines. Still need more work to fix portability across different OS.

**Closed by the3dfxdude** 2016-01-18 01:19 UTC
