### ISSUE TITLE
Mouse 'stuck' at left- and right-side of the screen (Fullscreen)

### ISSUE THREAD

**Issue by MicroVirus** [the3dfxdude/7kaa#46] opened 2015-07-06 09:36 UTC
Reported by Manu in http://www.7kfans.com/forums/viewtopic.php?f=13&t=775
When edge-scrolling left and right with the mouse, in fullscreen mode, it gets 'stuck' at the sides.

It seems as if the 'real' mouse is slightly outside of the window, so when you move it back it takes a while before it actually 'unsticks' from the border. This only happens left and right and not below or above.

**Comment by sraboy** [comment] 2015-07-22 10:41
I can see this a bit at full-screen just in the main menu too. I'm not sure if it's the same issue you guys are seeing, but it takes the cursor a little extra uumph to get moving.

Win 8.1 @ 1080p here.

**Comment by the3dfxdude** [comment] 2015-08-05 02:39
I have a hard time perceiving this one.

**Comment by taneltumanski** [comment] 2015-08-11 16:41
I have Win 8 @ 1080p and can confirm the problem.
The problem occurs because the mouse can move in the black, unused area if there is any on the sides.
I changed SDL_WINDOW_FULLSCREEN_DESKTOP to SDL_WINDOW_FULLSCREEN in vga_sdl.cpp and this bounded the mouse correctly to the UI box. 
I cannot test if this works on Linux/OSX but it fixed the problem in my PC.

**Comment by the3dfxdude** [comment] 2015-08-12 15:34
Thank you for your comment. I also do not expect a problem if the game window's aspect ratio matches the desktop resolution's aspect ratio. Forcing the requested window's resolution by a desktop resolution change would cause that. I believe that it is possible that when the desktop and game's aspect ratio do not match, that there may be issues with the virtual mouse coordinate system.

See point #3 in this SDL bug report:
https://bugzilla.libsdl.org/show_bug.cgi?id=2179

However, when I tried the game with mismatched aspect ratios, I could not visibly see a stuck mouse behavior. I might need to know more exactly on the version of windows, graphics card, and exact desktop resolution / aspect ratio.

I cannot change the fullscreen flag, because your suggestion will not work for all users--it was the SDL1.2 behavior which we changed to SDL2 to get this feature. I don't think we will need to do any kind of fallback (how to do it anyway?) but just fix the mouse code. In fact, the mouse code can be completely offloaded to SDL2 now, due to new mouse features. But I do want to identify the exact reason first before attempting changes.

**Comment by MicroVirus** [comment] 2015-08-12 15:38
I think that it is indeed that issue you pointed out. I've been down this road for 7kaa before. It doesn't seem like this'll get fixed, or at least not any time soon, since this has been open for years already.

We can try to experiment with workarounds where we manually call SDL to move the mouse whenever it'd go offscreen, or if we're feeling (very) brave dive into SDL2 and submit a fix.

Another option we can consider, independently, is allowing users to select which SDL mode they want (fullscreen or fullscreen-desktop).

**Comment by the3dfxdude** [comment] 2015-08-12 18:41
Actually, no I don't think we'd need to go that far.

Possibly something you didn't know about, was the game was/is supposed to be based on relative mouse movements. Please see OMOUSE.cpp:747. That was the original code. At some point I disabled that and switched to warping the mouse due to something happening with SDL. Please try defining MOUSE_RELATIVE and see if the problem goes away.

**Comment by taneltumanski** [comment] 2015-08-12 19:47
I tried that before when I noticed that code but its REALLY weird with it enabled.
The mouse is bound to the UI correctly MOST of the times.
Sometimes an invisible "wall" stops the mouse before reaching the edge. Its seemingly random, I haven't found any patterns to it yet. Sometimes the mouse stops at 50px from the edge, sometimes its half a screen away from the edge. It feels like the UI area is "moving", sometimes it moves only in X or Y direction, sometimes both.

**Comment by MicroVirus** [comment] 2015-08-12 19:49
Ahh right, yes, this makes me remember why I didn't feel like that was the solution at the time. Namely: SDL stops moving the actual mouse when you get to where it thinks the edge is and you get movement delta's of 0, 0, 0, 0, ...

**Comment by the3dfxdude** [comment] 2015-08-13 00:59
OK, so when in doubt, write a test case. :)

So I have had a hard time seeing the issue, so I wrote a stripped down case of what 7k does with blitting and the mouse, in hopes I can send to those who have an issue. But when I tested it on my square screen, which happens to use 1280x1024 (5:4), I happened to notice the bottom and top black bars, since the native aspect ratio is 4:3. I can see a /snapping/ effect at the bottom where when I hit the bottom, and then move the mouse up, the icon moves lower first, and then moves up. I have no idea why I didn't see this on a widescreen, but it might have something to do with the framerate.

I'm not 100% sure, so please reproduce in this test case on your screens as well. Here is the source file:
http://7kfans.com/downloads/sdl-mouse.c

If indeed it shows up here, at least we've isolated to how 7k uses SDL.

**Comment by the3dfxdude** [comment] 2015-08-13 02:35
OK the snapping action was a small error copying over code. Now it matches 7k even more closely, but I can't still see the problem. Still looking.

**Comment by taneltumanski** [comment] 2015-08-13 09:08
The problem is definitely visible on 1080p.
If you move the mouse to the left edge and then slowly start moving to the right edge then the mouse seems to be standing still for some time and then starts moving when it gets in the UI area.
The console output is correct in windowed mode but goes out of bounds in fullscreen mode.
I tried to move the mouse to the cur_x/cur_y location with SDL_WarpMouseInWindow but it generates a mouse motion event and introduces some weird behaviour like forcing the mouse aggressively towards 0,0.
This is surely an SDL problem and how the mouse and SDL_WINDOW_FULLSCREEN_DESKTOP interact when the game and desktop resolutions dont match. I'm surprised that this problem even occurs because this seems like a big deal in older games.

**Comment by the3dfxdude** [comment] 2015-08-13 18:06
Well again it could be a mouse sensitivity setting or framerate that makes it more perceptible to some people. But it becomes extremely clear that SDL is doing nothing to set boundaries of the texture for the mouse when you remove the bounding action that I built into the game. So when the window is fullscreen, there will be a dead zone the mouse is actually in.

With regard to the warping function. That is unfortunate, since it only works on actual coordinates of the window. However I have been looking at the 2D drawing functions, and it seems possible to get a scaling factor for the right coordinates: https://wiki.libsdl.org/SDL_RenderGetScale

I will try to work in a fix for that. It only needs to be applied when full screen, but we'll see how I can get it where I like.


BTW, I think I just decided to use the absolute position of the mouse to make windowed mode simply work seemlessly with the desktop mouse position. In fullscreen we could use relative mode instead. That is another option.

**Comment by the3dfxdude** [comment] 2015-08-13 21:25
Try this as a fix: http://7kfans.com/downloads/sdl-mouse-fix.c

It uses relative mouse movement only in fullscreen. If this works OK then I will make this change.

Warping the mouse just was going to be a problem. I figured out all the math to calculate the integer (x,y), but when it came down to it, I still had 1 pixel error coming back from SDL of what did with the mouse virtually. 1 pixel off is too much error. There really needs to be more controls using the logical coordinates if scaling is applied.

**Comment by taneltumanski** [comment] 2015-08-13 21:40
On first glance, this seems to do the trick. As an added bonus, this binds the mouse to my main monitor and doesn't let the mouse go to my other monitor. Will do some more testing tomorrow.

**Comment by the3dfxdude** [comment] 2015-08-13 21:55
If you need for any reason to confine the mouse to the game, use the grab option (ctrl-g). I should also enable it in fullscreen, but maybe it doesn't matter anymore. I'll review the input code.

**Comment by the3dfxdude** [comment] 2015-08-23 02:06
Committed a fix to bound the mouse better using relative mouse motions if input is grabbed.
https://github.com/the3dfxdude/7kaa/commit/ca879b2136be922f371c41e6be8cc43dbd68e606

**Closed by the3dfxdude** 2015-08-23 02:06 UTC

**Comment by MicroVirus** [comment] 2015-09-10 14:29
There is an issue with the fix on Windows 7 using SDL 2.0.3. When using SDL_SetRelativeMouseMode the mouse sensitivity changes, which is really really odd. I managed to narrow it down to that function by running some tests, both in 7kaa and using the3dfxdude's test-case.
One relative mouse mode is enabled, sensitivity becomes much lower. This effect occurs both in full-screen and windowed.
This... is really annoying.

**Comment by the3dfxdude** [comment] 2015-09-10 19:29
So SetRelativeMouseMode is for games that do not have a mouse cursor and rely on mouse for orientation of the player. If you wanted to use that while windowed, something would have to stop the desktop cursor from escaping the window. The command disables the desktop cursor by keeping the cursor centered on the window. This is actually what the original DInput code was doing.

In the original code, the game relied solely on relative mouse changes. Whenever you do this, you no longer can use the desktop mouse acceleration factor, and you'll have to use your own. I was tempted to turn that micky_to_displacement factor (whatever it was named) back on in the relative mode, but I could not discern a difference :) I can do it though and see what happens.

As we know prior, there is no real good way to do stretching and use absolute coordinates for the mouse. That is why there is distinct grab / no grab state in the code. If you turn on grab in windowed mode, it should behave the same as full screen.

**Comment by MicroVirus** [comment] 2015-09-10 20:24
Riiight, the acceleration must be what's different. I'm so used to it that I have a hard time discerning it from a 'slower' mouse.

Still, it's annoying that we can't directly have the user's desktop mouse settings in-game. If micky_to_displacement incorporates some form of acceleration, then it might be nice to have that as an option on/off in the future.

Thanks for clearing this up. I consider it solved, with a small item on the to-do list of allowing acceleration of the mouse.

**Comment by MicroVirus** [comment] 2015-09-12 17:53
The new commit with micky_to_displacement back into place doesn't feel well. It changes directionality of the mouse movement, which feels really odd. I changed it to compare x^2 + y^2 >= threshold^2 and then double each, but this also feels wrong, like the speed-up is very unpredictable. I'm currently experimenting to find what 'feels' right.

**Comment by the3dfxdude** [comment] 2015-09-13 23:04
I expected this, but like before, I didn't really notice anything. I was a bit against the triple_speed_threshold concept myself though, just as the devs were, since that could easily make the mouse fly across the screen unnaturally.

The reason why the function micky_to_displacement only worked on one axis is that DInput sent the data one axis at a time. It probable could be 2d vector.

I don't think it that you should have to move the mouse 'x' amount and then just "double" it. That is probably why it doesn't feel right. The displacement should be more like f(x) = C*x^3, where x is the original movement, f(x) is the 'accelerated' displacement, and C is some constant to modify the function's slope that feels natural enough. I recommend trying C of 2/3 to start. Of course I don't know how this would play out with integer math.

**Comment by MicroVirus** [comment] 2015-09-14 08:51
I was trying to find information on curves or algorithms for mouse acceleration. The curve Windows uses for instance was described in a document I can no longer seem to get my hands on, frustratingly. I experimented with various curves myself, including ones that smoothed and ones that handle integers by calculating in a double, truncating the decimals and store these for next time in an 'overflow' float variable, so I think I know of a way to handle at least the int vs float math. Anyway, I am still looking for things that feel right.

I should check if SDL sends two axes at a time or also only one. I should also check if there is a way to find the 'velocity' of the mouse, since this is the natural quantity to do acceleration on. I don't know in how far the displacement value in the message corresponds to velocity.

**Comment by the3dfxdude** [comment] 2015-09-14 14:22
The event in SDL gives you both axis.
https://wiki.libsdl.org/SDL_MouseMotionEvent

Isn't xrel/yrel the velocity then? Save enough samples, average them, and that is the average acceleration. Not sure if that matters though.

**Comment by sraboy** [comment] 2015-09-14 22:35
@MicroVirus 
This might be what you're looking for: https://web.archive.org/web/20110421045930/http://msdn.microsoft.com/en-us/windows/hardware/gg463319.aspx. Just an explanation of the acceleration without code so attribution should not be an issue. However, it's for XP and I see nothing newer.

**Comment by MicroVirus** [comment] 2015-09-15 10:31
@sraboy Yes! That's the one! Thanks for finding it; I didn't manage.
