### ISSUE TITLE
Soldiers defending their fort don't have the leaderiship bonus of their leader

### ISSUE THREAD

**Issue by jsynacek** [the3dfxdude/7kaa#92] opened 2017-09-25 10:30 UTC
When a fort's sortie option is turned on, when an enemy attacks the fort, soldiers leave it and defend it, but their leadership bonus is not applied. I consider this a bug that sort of makes the sortie option unusable and has been spoiling the game forever. I would say that, in this case, the soldiers should get a bonus as long as they stand in range of their leader (the fort where he is) as they would normally do.

**Comment by MicroVirus** [comment] 2017-09-25 10:43
That can indeed be considered a bug, because the leadership bonus itself is
specifically designed to also work when the general is inside a fort and
the unit is near the fort. There must be something with the way they are
mobilised that prevents proper functioning of the bonus.

I am curious though: how did you ascertain that the bonus isn't being
applied? Are you sure that it's not working?

On 25 Sep 2017 12:30, "Jan Synacek" <notifications@github.com> wrote:

When a fort's sortie option is turned on, when an enemy attacks the fort,
soldiers leave it and defend it, but their leadership bonus is not applied.
I consider this a bug that sort of makes the sortie option unusable and has
been spoiling the game forever. I would say that, in this case, the
soldiers should get a bonus as long as they stand in range of their leader
(the fort where he is) as they would normally do.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/the3dfxdude/7kaa/issues/92>, or mute the thread

**Comment by the3dfxdude** [comment] 2017-09-25 17:56
I have never seen proof it was intended to work this way. And I strongly believe the general must be on the field to get a bonus. That is always how I play the game, and knew when to get the leadership bonus by not relying on the auto-defense mechanism.

Please provide proof this was intended.

**Comment by MicroVirus** [comment] 2017-09-25 18:05
For the sceptics: https://github.com/the3dfxdude/7kaa/blob/1b1caa7c4463a24555f4e30750e6b24aaa80085a/src/OUNITAT.cpp#L836 OUNITAT.cpp lines 836-842 specifically looks for the leader unit when he's an overseer.

**Comment by jsynacek** [comment] 2017-09-25 18:48
First, I'd like to clarify that I meant the "Alert" option, not the sortie button... But I guess we understood each other.

> I am curious though: how did you ascertain that the bonus isn't being applied? Are you sure that it's not working?

Just try it with alert on, then try to sortie first and then fight. You can clearly observe that the bonus is not applied in the latter case.

Also, if you sortie the troops out of the fort and then put the general back in, I'm pretty sure they **do** get the bonus if they are close enough.

> I have never seen proof it was intended to work this way.
> ...
> Please provide proof this was intended.

Proof? What proof? I have no idea how it was **inteded** to work, and you have no idea too, unless you're the original author. I'm just saying that I consider it a bug. If anything, it makes it very easy to roll over the AI just because it uses the alert on.

If you don't think that this is a bug, you may consider this issue a request for improvement then.

**Comment by the3dfxdude** [comment] 2017-09-26 03:24
jsynacek, Don't be silly. I always thought it was only an effect while mobile. There would be evidence otherwise if it was intended different. And there is. It's clear it's an area effect in both mobile and non-mobile. Soldiers won't get an effect if they are disconnected from a fort with overseer, or they are too far away. So I'd check the automated defense function, and if the unit gets placed on the map without being disconnected, then there really isn't a problem.

**Comment by the3dfxdude** [comment] 2020-01-19 02:32
So I did describe what happened actually accurately, since the bonus only applied when the general was mobile, and never in the fort. It is clear in code, however, that the game was supposed to do more, and failed to implement the correct distance calculation.
In this case the defenders were not being assigned their leader. Should be fixed with 7103cb628f58a8638d47c26a2fbd35636b66529f

**Closed by the3dfxdude** 2020-01-19 02:32 UTC

**Comment by jsynacek** [comment] 2020-01-22 12:52
Thanks for fixing this!

**Comment by jsynacek** [comment] 2020-01-22 12:54
I would like to suggest another minor improvement. Generals, in my opinion, should apply the attack bonus also to themselves, as right now they are kind of an easy target. What do you think? I can file a separate issue for that if you would be willing to fix it. My guess is it would be an easy fix.

**Comment by J-Moravec** [comment] 2020-01-22 20:02
That would mean that a lot of nation would train peasant into soldier and make him general for a better leadership bonus. I think this is weird and just open doors for illogical behaviour.

**Comment by the3dfxdude** [comment] 2020-01-23 04:09
Yeah I agree where having generals automatically get the leadership damage bonus negates the point of having soldiers in the first place. 7k2 has heroes, which kind of gives this feature in a modest way, but does not do anything special for generals. Which also, creating something like a hero in 7k is not something I'll do either, because I don't want to turn the game into 7k2.

Which BTW, 7k2 does have the same range calculation bug and possibly assign leader on defense issue as 7k does. I'm not sure if they found this in the HD update. It severely puts a defender at disadvantage.
