### ISSUE TITLE
Segmentation Fault in the OpenALAudio Destructor on FreeBSD

### ISSUE THREAD

**Issue by kdhp** [the3dfxdude/7kaa#69] opened 2016-09-24 06:40 UTC
Assumptions about destructor ordering cause a conflict between this and OpenAL-Soft on FreeBSD, and possibly other platforms.

The OpenALAudio destructor can conflict with OpenAL-Soft's destructor causing a Segmentation Fault, or a failed assert (depending on the library version), at exit.  This happens when the OpenALAudio destructor is run after OpenAL-Soft's and attempts to call into the library; which attempts to access destroyed internal state causing the program to exit abnormally.

Standard Error (openal-soft-1.16.0)
```
lib: (EE) alc_cleanup: 1 device not closed
Segmentation fault
```

**Comment by the3dfxdude** [comment] 2016-09-25 00:41
I think I see the problem. I will work on this.

**Comment by MicroVirus** [comment] 2016-09-25 07:02
For my own clarity, is it true that the issue is that `Audio` (`OpenALAudio`) is a static global variable and thus its destructor gets called somewhere in the exit sequence while at the same time OpenAL-Soft has a destructor registered to call deinit on the library, and the order of these is undefined?

**Comment by kdhp** [comment] 2016-09-25 08:48
@MicroVirus Yes.

**Comment by the3dfxdude** [comment] 2016-10-11 00:31
Closing based on your contribution.

**Closed by the3dfxdude** 2016-10-11 00:31 UTC
