### ISSUE TITLE
Polish language wrong displayed

### ISSUE THREAD

**Issue by Lishoo** [the3dfxdude/7kaa#237] opened 2022-04-08 22:07 UTC
Hello, I just downloaded and run the 7KAA, and I was surprised that there are Polish captions, but unfortunately they are hard to understand because of the Polish special characters are wrong displayed, if there is a fix for that, it would be awesome, but if it is hard to fix, than maybe just replace the special characters to the normal substitute.
![2022-04-08](https://user-images.githubusercontent.com/1045996/162538250-678b31ae-0aac-4bde-8815-b9a91820d180.png)
![2022-04-08 (1)](https://user-images.githubusercontent.com/1045996/162538263-5ad47015-c277-4a18-b0c2-f6e70056cc84.png)
![2022-04-08 (2)](https://user-images.githubusercontent.com/1045996/162538277-0aabefe5-7d25-4b5f-bb55-55d0a7180124.png)

**Comment by the3dfxdude** [comment] 2022-04-08 23:23
I don't have this issue. So there is something about your installation. Possible things to check: old version, missing font files, and system settings.

**Comment by the3dfxdude** [comment] 2022-04-08 23:27
Polish is only in the current version, so can you tell me the distro and "echo $LANG"?

**Comment by the3dfxdude** [comment] 2022-04-08 23:35
So I initially thought you were on Linux, but yes, this seems to be what happens on Windows. This is provided by a third party library, so let me check on it.

**Comment by the3dfxdude** [comment] 2022-04-09 02:23
So the issue is Windows is returning something we don't recognize. I can't give you a workaround for this on your version. I will fix so that at least the locale is selectable on Windows in the next version and improve on it more later.

**Comment by the3dfxdude** [comment] 2022-04-09 03:15
You will be able to force the game to load the correct fonts so the accent marks are placed correctly in the next version. To do so, go to %appdata%\7kfans.com\7kaa  and create a file called config.txt and open in notepad. Then add the line:
locale=pl_PL

Closing on f15e48ca14e3f4d1b1d1a6ab330197bc146ad1d1

**Closed by the3dfxdude** 2022-04-09 03:15 UTC

**Comment by Lishoo** [comment] 2022-04-09 09:50
Thank you very much :)

**Comment by Lishoo** [comment] 2022-04-09 18:03
Hi, I just compiled the game from sources and run it using SKDATA=data ./src/7kaa but the game is always in English, how to force the polish language?

**Comment by the3dfxdude** [comment] 2022-04-10 01:31
As mentioned before, but the path on linux is $HOME/.local/share/7kfans.com/7kaa. Create the config.txt there.

It does mean the LANG environment variable is now being ignored, and I'm not sure what to do since some people may be expecting LANG to be used, but some where complaining that the game was using their native language and preferred English instead.

**Comment by Zalewa** [comment] 2022-04-30 11:56
> You will be able to force the game to load the correct fonts so the accent marks are placed correctly in the next version. To do so, go to %appdata%\7kfans.com\7kaa and create a file called config.txt and open in notepad. Then add the line: locale=pl_PL

This doesn't solve the problem for me. The `locale=` setting works in general because when I set it to `locale=ru` I can see that the game uses a different font, but when I set it to `locale=pl` or `locale=pl_PL`, it doesn't fix the diacritics. They're just as broken as on OP's screenshots. **Windows 10** platform, game versions **2.15.4p1** and **2.15.5**.

But - is there a way to force the game to just use English, short of deleting the `locale\pl` directory? `locale=C`, `locale=en_EN`, `locale=en`, `locale=en_US` don't change the language. Notably, `locale=ru` doesn't set the language it should either.

**Comment by Zalewa** [comment] 2022-05-26 21:50
> is there something wrong with your installation?

Adding the SHA1 checksums from **2.15.5** with older SDL due to the mouse scroll bug.
[7kaa.sha.gz](https://github.com/the3dfxdude/7kaa/files/8782329/7kaa.sha.gz)
